[package]
name = "phixiv"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.11"
isbot = "0.1"
lambda_http = { version = "0.7", default-features = false, features = ["apigw_http"] }
lambda_runtime = "0.7"
lazy_static = "1.4.0"
minify-html = "0.10"
regex = "1"
reqwest = { version = "0.11.13", default-features = false, features = ["rustls-tls", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["macros"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }
url = "2"
urlencoding = "2.1.2"

[features]
small_images = []
