[package]
name = "phixiv"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = { version = "0.7", default-features = false, features = ["apigw_http"] }
lambda_runtime = "0.7"
reqwest = { version = "0.11.13", default-features = false, features = ["rustls-tls"] }
scraper = "0.13.0"
serde = { version = "1", features = ["derive"] }
tera = "1"
tokio = { version = "1", features = ["macros"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }
url = "2"

