name: Deploy Beta
on:
  push:
    branches:
    - beta
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd ${{ secrets.REPOSITORY_DIRECTORY }}
          git checkout beta
          git pull
          ${{ secrets.CARGO_PATH }} +nightly -Z sparse-registry build --release
          echo ${{ secrets.SUDO_PASSWORD }} | sudo -S mv ./target/release/phixiv /usr/local/bin/phixiv-beta
          echo ${{ secrets.SUDO_PASSWORD }} | sudo -S systemctl restart phixiv-beta